export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh



# Source all files with the .zsh exrension in the zsh/ directory
for config ($ZSH/**/*.zsh) source $config

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

  # Set Spaceship ZSH as a prompt
  autoload -U promptinit; promptinit
  prompt spaceship
